### ISSUE TITLE
ReferenceError: Error resolving module '/var/task/@aws-sdk/client-eventbridge' 

### ISSUE THREAD

**Issue by ymwjbxxq** [awslabs/llrt#2]
Hello,

**Lambda config:**

```
  Function:
    MemorySize: 256
    Architectures: ["arm64"]
    Runtime: provided.al2
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:LLRT:1
 ```

**Deployed with**
```
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - '@aws-sdk/client-eventbridge'
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/util-dynamodb'
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - list.ts
 ```
**Packages:**
```
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.433.0",
    "@aws-sdk/util-dynamodb": "^3.433.0",
    "@aws-sdk/client-eventbridge": "^3.433.0",
    "uuid": "^9.0.1"
  }
````
**Log:**
```
INIT_START Runtime Version: provided:al2.v25 Runtime Version ARN: arn:aws:lambda:eu-central-1::runtime:dce29199fb5887a2c4fceaa2f34d395ba43a74a6895b381cb9383b1c7f3b5875
Binary launched
Decompressing using 2 threads
Extraction time: 13.7280 ms
Extraction + write time: 18.8690 ms
Starting app
ReferenceError: Error resolving module '/var/task/@aws-sdk/client-eventbridge' from '' at <anonymous> (/var/task/insertToSync.js:1:614)
START RequestId: 234d277d-adc9-58b0-a831-7acab3e3ad38 Version: $LATEST
Unknown application error occurred Runtime.Unknown
END RequestId: 234d277d-adc9-58b0-a831-7acab3e3ad38
REPORT RequestId: 234d277d-adc9-58b0-a831-7acab3e3ad38 Duration: 362.75 ms Billed Duration: 363 ms Memory Size: 128 MB Max Memory Used: 12 MB
```
