### ISSUE TITLE
Lambda to DynamoDB Local Connection Issue with @aws-sdk/client-dynamodb: Invalid Authority Error

### ISSUE THREAD

**Issue by bypabloc** [awslabs/llrt#215]
### Issue Title
Connection Issue with DynamoDB Local Using `@aws-sdk/client-dynamodb` in Lambda

### Description
I am experiencing an issue attempting to connect a Lambda (using the image `amazon/aws-lambda-provided:al2023`) with DynamoDB Local. I conducted three different tests within the same Lambda script to ensure a connection and fetch a list of tables from DynamoDB Local.

#### 1. Without Authorization (Using `fetch`)
I tried making a request to DynamoDB Local without authorization using `fetch`, which resulted in an expected error indicating the absence of a valid authentication token.

#### 2. With Fake Authorization (Using `fetch`)
When making a request with fake authorization (false credentials) using `fetch`, the connection was successful, and the list of tables was correctly received.

#### 3. Using `@aws-sdk/client-dynamodb`
Using `@aws-sdk/client-dynamodb` with proper configurations, including credentials and local endpoint, resulted in an "invalid authority" error.

### Environment Configuration
**Dockerfile:**
```dockerfile
FROM amazon/aws-lambda-provided:al2023.2024.02.07.17
COPY bootstrap ${LAMBDA_RUNTIME_DIR}/bootstrap
RUN chmod +x ${LAMBDA_RUNTIME_DIR}/bootstrap
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ${PATH_LAMBDA}/dist/ ${LAMBDA_TASK_ROOT}
EXPOSE 8080
CMD ["index.handler"]
```

**docker-compose.yml:**
```yml
version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "9100:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal

  product:
    build: .
    container_name: lambda-product
    environment:
      PATH_LAMBDA: './lambdas/product'
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      REGION: us-west-2
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: yourAccessKeyId
      AWS_SECRET_ACCESS_KEY: yourSecretAccessKey
      AWS_SESSION_TOKEN: yourSessionToken
```

### Issue
The "invalid authority" error seems to indicate a specific problem with the `@aws-sdk/client-dynamodb` library when trying to connect to DynamoDB Local from a Lambda environment using the described setup. Previous tests with `fetch` suggest that the network configuration and credentials are correct, but there is something specific in the interaction with `@aws-sdk/client-dynamodb` that causes this failure.

### Request
Has anyone else experienced this issue or has suggestions on how to resolve it? Any guidance or assistance would be greatly appreciated.
