### ISSUE TITLE
S3:  "errorMessage": "not a function",

### ISSUE THREAD

**Issue by ymwjbxxq** [awslabs/llrt#25]
Hello,

A perfectly Node20 Lambda can upload a file into S3
When I switch to LLRT, I cannot do it anymore.

**SAM TEMPLATE:**
```
UploadToS3:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Architectures: ["arm64"]
      MemorySize: 128
      Runtime: provided.al2
      # MemorySize: 1024
      # Runtime: nodejs20.x
      .....
   Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - '@aws-sdk/client-s3'
        Minify: true
        Target: "es2020"
        Sourcemap: false
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
        - uploadToS3.ts
```

**LAMBDA:**
```
import { S3Client, ClientDefaults, PutObjectCommand, PutObjectCommandInput, ObjectCannedACL } from "@aws-sdk/client-s3";

const clientDefaults: ClientDefaults = {
  region: process.env.AWS_REGION,
};
const s3Client = new S3Client(clientDefaults);

export const handler = async (event) => {
  console.debug("event", JSON.stringify(event));

  try {
    const jsonFile = {
      "data": event,
    }
    const params: PutObjectCommandInput = {
      Bucket: process.env.BUCKET_NAME,
      Key: `path/${event.id}.json`,
      Body: JSON.stringify(jsonFile),
      ACL: ObjectCannedACL.bucket_owner_full_control,
      ContentType: "application/json",
    };
    const command = new PutObjectCommand(params);
    await s3Client.send(command);
  } catch (error) {
    console.error(error);
  }
};
```

**LOG:**
```
{
  "errorType": "TypeError",
  "errorMessage": "not a function",
  "stackTrace": [
    "    at C (/var/task/uploadToS3.mjs:1:159)",
    "    at startProcessEvents (@llrt/runtime:5:159)",
    ""
  ],
  "requestId": "c03887d1-66d8-476b-ada6-cd8e1aaadfc6"
}

{
  "time": "2023-11-25T08:34:30.527Z",
  "type": "platform.runtimeDone",
  "record": {
    "requestId": "c03887d1-66d8-476b-ada6-cd8e1aaadfc6",
    "status": "success",
    "metrics": {
      "durationMs": 2.25,
      "producedBytes": 0
    }
  }
}
{
  "time": "2023-11-25T08:34:30.529Z",
  "type": "platform.report",
  "record": {
    "requestId": "c03887d1-66d8-476b-ada6-cd8e1aaadfc6",
    "status": "success",
    "metrics": {
      "durationMs": 2.556,
      "billedDurationMs": 44,
      "memorySizeMB": 128,
      "maxMemoryUsedMB": 29,
      "initDurationMs": 40.651
    }
  }
}
```
